[package]
name = "unstyled"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["Yannik_Sc"]
description = "Unstyled is just another library which allows to write scoped CSS styles in Rust"

[lib]
proc-macro = true

[dependencies]

[dev-dependencies]
leptos = "0.4"
